version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
  redis:
    container_name: spree-redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - './docker/redis:/data'
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq

volumes:
  bundle:
